// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"go-crud-db-p2/config"
	"go-crud-db-p2/internal"
	"go-crud-db-p2/internal/adapters/primary/http/platform"
	platform4 "go-crud-db-p2/internal/adapters/secondary/email/platform"
	platform2 "go-crud-db-p2/internal/adapters/secondary/mongo/platform"
	platform5 "go-crud-db-p2/internal/adapters/secondary/postgres/platform"
	"go-crud-db-p2/internal/adapters/security"
	platform3 "go-crud-db-p2/internal/core/services/platform"
)

// Injectors from wire.go:

func InitializeMongoApp(ctx context.Context, cfg config.Config) (*platform.PlatformHandler, error) {
	engine := provideGinEngine(cfg)
	routerGroup := provideGinRouterGroup(engine)
	database, err := provideMongoDatabase(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := platform2.NewUserRepository(database)
	objectIDGenerator := platform2.NewObjectIDGenerator()
	bcryptPasswordHasher := security.NewBcryptPasswordHasher()
	jwtManager := security.NewJWTManager(cfg)
	googleOAuth := security.NewGoogleOAuth(cfg)
	memoryStateStore := security.NewMemoryStateStore(cfg)
	systemClock := platform3.NewSystemClock()
	iEmailSender := platform4.NewEmailSender(cfg)
	authService := platform3.NewAuthService(userRepository, cfg, objectIDGenerator, bcryptPasswordHasher, jwtManager, googleOAuth, memoryStateStore, systemClock, iEmailSender)
	todoRepository := platform2.NewTodoRepository(database)
	todoService := platform3.NewTodoService(todoRepository, cfg, objectIDGenerator, systemClock)
	platformHandler := platform.NewPlatformHandler(routerGroup, engine, authService, todoService, jwtManager)
	return platformHandler, nil
}

func InitializePostgresApp(ctx context.Context, cfg config.Config) (*platform.PlatformHandler, error) {
	engine := provideGinEngine(cfg)
	routerGroup := provideGinRouterGroup(engine)
	pool, err := providePostgresPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	userRepository := platform5.NewUserRepository(pool)
	uuidGenerator := platform5.NewUUIDGenerator()
	bcryptPasswordHasher := security.NewBcryptPasswordHasher()
	jwtManager := security.NewJWTManager(cfg)
	googleOAuth := security.NewGoogleOAuth(cfg)
	memoryStateStore := security.NewMemoryStateStore(cfg)
	systemClock := platform3.NewSystemClock()
	iEmailSender := platform4.NewEmailSender(cfg)
	authService := platform3.NewAuthService(userRepository, cfg, uuidGenerator, bcryptPasswordHasher, jwtManager, googleOAuth, memoryStateStore, systemClock, iEmailSender)
	todoRepository := platform5.NewTodoRepository(pool)
	todoService := platform3.NewTodoService(todoRepository, cfg, uuidGenerator, systemClock)
	platformHandler := platform.NewPlatformHandler(routerGroup, engine, authService, todoService, jwtManager)
	return platformHandler, nil
}

// wire.go:

var CoreAppSet = wire.NewSet(
	provideGinEngine,
	provideGinRouterGroup, internal.ServiceSet, internal.HandlerSet,
)
